apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: newindia90/reddit:latest
        ports:
        - containerPort: 3000
